version: '3.8'

services:
  main_bot:
    build: .
    container_name: main_bot
    restart: always
    env_file:
      - .env
    command: python -m app.main
    volumes:
      - ./data.db:/usr/src/app/data.db

  system_bot:
    build: .
    container_name: system_bot
    restart: always
    env_file:
      - .env
    command: python -m app.system_main
    depends_on:
      - main_bot
    volumes:
      - ./data.db:/usr/src/app/data.db
